# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 745fc018394b5e6117647065fa1bf9787721cf4b616fe6d0718cc87a2d741ced847351442a0d4a71af8d0655fdff22ba54b6aebe2105ead3b5e9a116621ced59

test:
  secret_key_base: c5406a615f5bab56c9481bf8347493b16cbed2c8390a732f77eba035d83488a9472bd811e8013e23bd7f8f4806abfcd32b4aaeece18033a574e6a950e035fa9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
